### ISSUE TITLE
Missing PDBs

### ISSUE THREAD

**Issue by sawilde** [jupaol/NCastor#1]
Whilst investigating issue https://github.com/sawilde/opencover/issues/79 I notice that I can't get your project to build properly due to missing PDBs which your build is trying to copy.

```
Unable to copy file "C:\Personal\ncastor.git\working\Solutions\NCastor.AutoBuilder.Runner\Tasks\MSBuild Extension 
Pack\MSBuild.ExtensionPack.BizTalk.pdb" to "bin\Debug\Tasks\MSBuild Extension Pack\MSBuild.ExtensionPack.BizTalk.pdb". Could 
not find file 'C:\Personal\ncastor.git\working\Solutions\NCastor.AutoBuilder.Runner\Tasks\MSBuild Extension 
Pack\MSBuild.ExtensionPack.BizTalk.pdb'.
```

I suspect your .gitignore file is excluding all .pdbs but you may need to be more selective on which sub-folders you apply it to.

As I am investigating an issue related to your project I need it to build as-is so I do not introduce any other issues.

**Comment by jupaol** [comment]
Hi
It is fixed now
